user openresty;
events { }
http {
    include     mime.types;
    root        html;
    error_page  405 = $request_uri;
    client_body_in_file_only clean;
    server {
        listen  127.0.0.82:9082;
        listen  127.0.0.83:9083;
        listen  127.0.0.84:9084;
    }
}
